---
# file: roles/calibration/tasks/main.yaml

- name: Install distribution - release - machine prerequisites
  include_tasks: '{{ ansible_distribution|lower }}_{{ ansible_distribution_release }}.yaml'

- name: Run Spectre Meltdown checker
  raw: 'spectre-meltdown-checker --no-color'
  register: spectre_meltdown_output
  tags: run-spectre-meltdown-checker

- debug: var=spectre_meltdown_output.stdout_lines
  tags: run-spectre-meltdown-checker

- name: x86 specific
  import_tasks: x86_64.yaml
  when: ansible_machine == 'x86_64'
