---
# file: common/tasks/main.yml

- name: Install required common system packages
  apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
    state: 'latest'
    cache_valid_time: 3600

- name: Set /bin/sh to bash instead of dash
  alternatives:
    name: sh
    link: /bin/sh
    path: /bin/bash
