---
# file: roles/sut/tasks/main.yaml

- name: Install distribution - release - machine prerequisites
  include_tasks: '{{ ansible_distribution|lower }}_{{ ansible_distribution_release }}.yaml'

- name: Taishan aarch64 specific
  import_tasks: taishan_workaround.yaml
  when: taishan_workaround is defined

- name: Copy 80-vpp.conf
  file:
    src: '/dev/null'
    dest: '/etc/sysctl.d/80-vpp.conf'
    state: 'link'
  become: yes
  tags: copy-80-vpp

- name: Get kernel-kvm version
  shell: "apt-cache depends -i linux-image-kvm | grep Depends: | cut -d' ' -f4"
  register: 'linux__image_kvm_read'
  tags: install-kernelvm

- name: Download kernel-kvm
  shell: "apt-get -y download {{ linux__image_kvm_read.stdout }}"
  args:
    warn: false # Prevent warning as APT module does not support download.
  register: 'linux__image_kvm_download'
  when: 'linux__image_kvm_read'
  tags: install-kernelvm

- name: Unpack kernel-kvm
  shell: "dpkg --extract {{ linux__image_kvm_read.stdout }}_*.deb /opt/"
  when: 'linux__image_kvm_download'
  tags: install-kernelvm

